---
- name: manage Beats services
  ansible.builtin.service:
    name: "{{ __beats_package_name[item] }}"
    state: "{{ lookup('vars', item ~ '_service_state') }}"
    enabled: "{{ lookup('vars', item ~ '_service_enabled') }}"
  when: (lookup('vars', item ~ '_service_enabled') | bool) or
        (lookup('vars', item ~ '_service_state') != 'stopped')
  loop: "{{ __available_beats }}"
