---
- name: Converge
  hosts: all
  become: true
  vars:
    # install and manage Auditbeat service
    auditbeat_install_state: present
    auditbeat_service_enabled: true
    auditbeat_service_state: started

    auditbeat_config:
      output.file:
        path: "/var/log/auditbeat"
        filename: auditbeat

      logging.level: warning
      logging.metrics.enabled: false

      auditbeat.modules:
        # https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-module-auditd.html
        # this replaces the Auditd program (should not run parallel to Auditd)
        - module: auditd
          resolve_ids: true
          failure_mode: silent
          backlog_limit: 8196
          rate_limit: 0
          include_raw_message: false
          include_warnings: false
          audit_rule_files: [ '${path.config}/audit.rules.d/*.conf' ]
          # taken from: https://github.com/Neo23x0/auditd/blob/master/audit.rules
          audit_rules: |
            # Self Auditing ---------------------------------------------------------------

            ## Audit the audit logs
            ### Successful and unsuccessful attempts to read information from the audit records
            -w /var/log/audit/ -k auditlog

            ## Auditd configuration
            ### Modifications to audit configuration that occur while the audit collection functions are operating
            -w /etc/audit/ -p wa -k auditconfig
            -w /etc/libaudit.conf -p wa -k auditconfig
            -w /etc/audisp/ -p wa -k audispconfig

            ## Monitor for use of audit management tools
            -w /sbin/auditctl -p x -k audittools
            -w /sbin/auditd -p x -k audittools
            -w /usr/sbin/augenrules -p x -k audittools

            # Filters ---------------------------------------------------------------------

            ### We put these early because audit is a first match wins system.

            ## Ignore SELinux AVC records
            -a always,exclude -F msgtype=AVC

            ## Ignore current working directory records
            -a always,exclude -F msgtype=CWD

            ## Ignore EOE records (End Of E

        # https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-module-file_integrity.html
        - module: file_integrity
          paths:
            - /bin
            - /usr/bin
            - /sbin
            - /usr/sbin
            - /etc
          exclude_files:
            - '(?i)\.sw[nop]$'
            - '~$'
            - '/\.git($|/)'
            - '/etc/mtab'
          scan_at_start: true
          scan_rate_per_sec: 50 MiB
          max_file_size: 300 MiB
          hash_types: [blake2b_256]
          recursive: true

        # https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-module-system.html
        - module: system
          datasets:
            - package  # Installed, updated, and removed packages
          period: 30m  # The frequency at which the datasets check for changes

        - module: system
          datasets:
            - host     # General host information, e.g. uptime, IPs
            - login    # User logins, logouts, and system boots.
            - process  # Started and stopped processes
            - user     # User information
          state.period: 6h
          user.detect_password_changes: true
          # File patterns of the login record files.
          login.wtmp_file_pattern: /var/log/wtmp*
          login.btmp_file_pattern: /var/log/btmp*

  roles:
    - role: aisbergg.beats
